# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "4.15.1"
    }
}
    
    backend "s3" {
    bucket = "terraform-code-repo-for-state-files-2w-competency"
    key            = "terraform/modules/security/terraform.tfstate"
    region = "us-east-1"
   }
  }
