# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.15.1"
    }
  }

  backend "s3" {
    bucket = "terraform-three-tier-demo-dakota"
    key    = "application/terraform.tfstate"
    region = "us-east-1"
  }
}
